.github/pull_request_template.md
- Convert PR template unordered list to task list
=> Convert PR template proposed changes list from unordered list to task list

.gitignore
N/A
- Replace .env* with .env and .env*.local
=> Allow .env* files but ignore .env*.local

.github/workflows/ci.yml
=> Update ci job name to "check formatting & lint"

next.config.mjs, package-lock.json, package.json
=> configure static export

.lintstagedrc.js, package.json
=> fix: duplicate lintstaged config

.vscode/extensions.json, package-lock.json
=> Set up VSCode extension recommendations

.vscode/settings.json, package-lock.json
=> Configure VSCode formatting settings

.github/ISSUE_TEMPLATE/user_story.md, .prettierignore
=> Fix user story issue template

package-lock.json, package.json, src/components/LocationForm.js, src/components/MapForm.js, src/components/QuestForm.js, src/pages/create/index.js
=> Quest gen page 

src/components/CharacterForm.js, src/components/GeneratedAsset.js, src/components/LocationForm.js, src/components/MapForm.js, src/components/QuestForm.js, src/pages/create/index.js
Fixes [75](https://github.com/tabletop-generator/ttg-client/issues/75)
=> Quest form fix

src/cognitoAuthConfig.js, src/components/Layout.js, src/components/Layout.jsx, src/pages/_app.js
=> fix: persist authentication across browsing contexts

src/api.js, src/cognitoAuthConfig.js
Fixes [101](https://github.com/orgs/tabletop-generator/projects/1/views/12?sliceBy%5Bvalue%5D=JulAleks&pane=issue&itemId=96041326&issue=tabletop-generator%7Cttg-client%7C101)
Since `postUser(userData)` involves an API request, making the function **async** ensures we wait for the request to complete before moving forward.
```js
const response = await fetch(`${apiUrl}/v1/users`, { ... })
```js
import { postUser } from "@/api";
- No previous code, nor comments were removed.
- New block was introcued:
- Extracts user info (ID token & email) when the user logs in.
- Constructs a user **data object** with these details.
- Uses a `try-catch` block to call `postUser(userData)`.
- If successful:
- `200` → Logs "User already exists" with API response.
- `201` → Logs …
=> added an empty post request when user logs in to check if the exist 

src/components/auth/withAuth.js, src/pages/_app.js, src/pages/create/index.js, src/pages/discover/[id].js, src/pages/discover/index.js, src/pages/index.js, src/pages/profile/[id].js, src/pages/profile/index.js
**Issue 100: https://github.com/orgs/tabletop-generator/projects/1/views/12?pane=issue&itemId=95908433&issue=tabletop-generator%7Cttg-client%7C100**
Fixes #100 
=> Forced auth on all subpages

src/api.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/EditableProfileHeader.js, src/components/Profile/ProfileHeader.js, src/pages/profile/index.js
normalized user info to be fetched on window reload and set up env to accept Patch and Delete APIs
Fixes #113
=> normalized user info to be fetched on window reload and set up env to accept Patch and Delete apis

src/api.js, src/components/CharacterForm.js, src/components/GeneratedAsset.js
=> Changes to character API

src/api.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/AssetGrid.js, src/pages/profile/[id].js, src/pages/profile/index.js
Fixes #46 
Fixes #51 
Fixes #58 
=> Connected UI with backend patch asset:name, description, visability

src/api.js, src/components/LocationForm.js, src/components/MapForm.js, src/components/QuestForm.js
=> Presentation 2 api fixes

README.md, package.json, src/components/GeneratedAsset.js, src/components/QuestForm.js
=> Fix quest description display error

src/cognitoAuthConfig.js, src/components/RetryBanner.js, src/utils/retryHandler.js
=> added retry banner if server fails as well as just user fetching error

src/components/Layout.jsx
Fix for the navbar highlighting using the existing navigation array in Layout.jsx
=> fix navbar highlight when loading new page

src/api.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/CollectionDetails.js, src/components/Profile/CollectionGrid.js, src/components/Profile/CreateCollectionForm.js, src/components/Profile/EditCollectionForm.js, src/pages/profile/[id].js, src/pages/profile/index.js, src/styles/CollectionDetails.module.css
Fixes tabletop-generator/issues#52 
Fixes tabletop-generator/ttg-client#135 
Fixes tabletop-generator/ttg-client#137
**To manually close**
https://github.com/tabletop-generator/issues/issues/5?issue=tabletop-generator%7Cissues%7C60
https://github.com/tabletop-generator/ttg-client/issues/130
https://github.com/tabletop-generator/ttg-client/issues/135
https://github.com/tabletop-generator/ttg-client/issues/137
https://github.com/tabletop-generator/ttg-client/issues/131
https://github.com/tabletop-generator/ttg-client/issues/133
https://github.com/tabletop-generator/ttg-client/issues/132
**Close stories manually**
https://github.com/tabletop-generator/issues/issues/2 
https://github.com/tabletop-generator/issues/issues/4 …
=> added collection modules

src/api.js, src/cognitoAuthConfig.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/AssetGrid.js, src/components/Profile/CollectionDetails.js, src/components/Profile/EditableProfileHeader.js, src/pages/profile/[id].js, src/pages/profile/index.js
Fixes #142 
Fixes #134 
Fixes #38 
Fixes #140  
Fixes #36  
Fixes #57 
Fixes #52  
Close stories:
https://github.com/tabletop-generator/issues/issues/17
https://github.com/tabletop-generator/issues/issues/27
https://github.com/tabletop-generator/issues/issues/10
https://github.com/tabletop-generator/issues/issues/3
https://github.com/tabletop-generator/issues/issues/23
https://github.com/tabletop-generator/issues/issues/17
https://github.com/tabletop-generator/issues/issues/22
https://github.com/tabletop-generator/issues/issues/30
=> updated collections, delete asset, and user update

src/components/Profile/AssetDetailsCard.js, src/components/Profile/AssetGrid.js, src/components/Profile/CollectionDetails.js, src/components/Profile/CollectionGrid.js, src/components/Profile/ProfileHeader.js, src/pages/profile/index.js, src/pages/profile/user/[hashedEmail].js
Fixes #44 
Fixes #40 
Fixes #98 
=> Added profile viewing for other creators

src/components/Profile/CollectionGrid.js
Fix for image caching and collection image previews 
=> added caching and better loading for collection images

src/api.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/CollectionDetails.js, src/components/Profile/CollectionGrid.js, src/components/Profile/CommentsSection.js, src/styles/CollectionDetails.module.css
Fixes #63 
Fixes #64 
Fixes #65  
Fixes #150 
- Users can comment on their own private assets.
- Users can comment on public assets; these comments will be public and visible to all users.
- Users can edit or delete their own comments.
- Users who own an asset can delete any comment posted on their asset.
- Users who do not own the asset or the comment will not see the edit or delete options.
=> added commenting functionality and fixed the collection star bug

src/components/Profile/AssetDetailsCard.js
**Visibility toggle tweaks**
Fixes #151 
=> Moved asset visibility from submenu to main component

src/cognitoAuthConfig.js, src/components/Layout.jsx
Attempt number 3, we got it this time guys
Fixes #143 
=> Fixed signout bug for real this time

src/api.js, src/components/PinterestGrid.js, src/components/Profile/AssetDetailsCard.js, src/components/Profile/CommentsSection.js, src/pages/discover/[id].js
Unauthorized asset preview
Fixes #156 
=> Unauthorized asset preview

src/components/CharacterForm.js, src/components/LoadingAnimation.js, src/components/LocationForm.js, src/components/MapForm.js, src/components/QuestForm.js, src/styles/tailwind.css
=> Added loading animation

src/components/PinterestGrid.jsx, src/components/Profile/AssetDetailsCard.jsx, src/components/Profile/CollectionDetails.jsx
=> Remove-sharing

src/components/SearchFeatures.jsx
Changes to main page dropdowns when browsers are in light mode
=> light mode tweaks
